// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_messages.proto

package ohmdb.messages;

public final class ControlMessages {
  private ControlMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StartServiceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string service_name = 1;
    /**
     * <code>optional string service_name = 1;</code>
     */
    boolean hasServiceName();
    /**
     * <code>optional string service_name = 1;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>optional string service_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    // optional int32 service_port = 2;
    /**
     * <code>optional int32 service_port = 2;</code>
     */
    boolean hasServicePort();
    /**
     * <code>optional int32 service_port = 2;</code>
     */
    int getServicePort();

    // optional string service_argv = 3;
    /**
     * <code>optional string service_argv = 3;</code>
     */
    boolean hasServiceArgv();
    /**
     * <code>optional string service_argv = 3;</code>
     */
    java.lang.String getServiceArgv();
    /**
     * <code>optional string service_argv = 3;</code>
     */
    com.google.protobuf.ByteString
        getServiceArgvBytes();
  }
  /**
   * Protobuf type {@code ohmdb.messages.StartService}
   */
  public static final class StartService extends
      com.google.protobuf.GeneratedMessage
      implements StartServiceOrBuilder {
    // Use StartService.newBuilder() to construct.
    private StartService(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StartService(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StartService defaultInstance;
    public static StartService getDefaultInstance() {
      return defaultInstance;
    }

    public StartService getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StartService(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serviceName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              servicePort_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              serviceArgv_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_StartService_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_StartService_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ohmdb.messages.ControlMessages.StartService.class, ohmdb.messages.ControlMessages.StartService.Builder.class);
    }

    public static com.google.protobuf.Parser<StartService> PARSER =
        new com.google.protobuf.AbstractParser<StartService>() {
      public StartService parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StartService(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StartService> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string service_name = 1;
    public static final int SERVICE_NAME_FIELD_NUMBER = 1;
    private java.lang.Object serviceName_;
    /**
     * <code>optional string service_name = 1;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string service_name = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string service_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 service_port = 2;
    public static final int SERVICE_PORT_FIELD_NUMBER = 2;
    private int servicePort_;
    /**
     * <code>optional int32 service_port = 2;</code>
     */
    public boolean hasServicePort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 service_port = 2;</code>
     */
    public int getServicePort() {
      return servicePort_;
    }

    // optional string service_argv = 3;
    public static final int SERVICE_ARGV_FIELD_NUMBER = 3;
    private java.lang.Object serviceArgv_;
    /**
     * <code>optional string service_argv = 3;</code>
     */
    public boolean hasServiceArgv() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string service_argv = 3;</code>
     */
    public java.lang.String getServiceArgv() {
      java.lang.Object ref = serviceArgv_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceArgv_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string service_argv = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceArgvBytes() {
      java.lang.Object ref = serviceArgv_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceArgv_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serviceName_ = "";
      servicePort_ = 0;
      serviceArgv_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, servicePort_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getServiceArgvBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, servicePort_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getServiceArgvBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ohmdb.messages.ControlMessages.StartService parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.messages.ControlMessages.StartService parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.StartService parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.messages.ControlMessages.StartService parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.StartService parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.messages.ControlMessages.StartService parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.StartService parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ohmdb.messages.ControlMessages.StartService parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.StartService parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.messages.ControlMessages.StartService parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ohmdb.messages.ControlMessages.StartService prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ohmdb.messages.StartService}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ohmdb.messages.ControlMessages.StartServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_StartService_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_StartService_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ohmdb.messages.ControlMessages.StartService.class, ohmdb.messages.ControlMessages.StartService.Builder.class);
      }

      // Construct using ohmdb.messages.ControlMessages.StartService.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        servicePort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        serviceArgv_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_StartService_descriptor;
      }

      public ohmdb.messages.ControlMessages.StartService getDefaultInstanceForType() {
        return ohmdb.messages.ControlMessages.StartService.getDefaultInstance();
      }

      public ohmdb.messages.ControlMessages.StartService build() {
        ohmdb.messages.ControlMessages.StartService result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ohmdb.messages.ControlMessages.StartService buildPartial() {
        ohmdb.messages.ControlMessages.StartService result = new ohmdb.messages.ControlMessages.StartService(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.servicePort_ = servicePort_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serviceArgv_ = serviceArgv_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ohmdb.messages.ControlMessages.StartService) {
          return mergeFrom((ohmdb.messages.ControlMessages.StartService)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ohmdb.messages.ControlMessages.StartService other) {
        if (other == ohmdb.messages.ControlMessages.StartService.getDefaultInstance()) return this;
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000001;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasServicePort()) {
          setServicePort(other.getServicePort());
        }
        if (other.hasServiceArgv()) {
          bitField0_ |= 0x00000004;
          serviceArgv_ = other.serviceArgv_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ohmdb.messages.ControlMessages.StartService parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ohmdb.messages.ControlMessages.StartService) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string service_name = 1;
      private java.lang.Object serviceName_ = "";
      /**
       * <code>optional string service_name = 1;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string service_name = 1;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string service_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service_name = 1;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_name = 1;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_name = 1;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }

      // optional int32 service_port = 2;
      private int servicePort_ ;
      /**
       * <code>optional int32 service_port = 2;</code>
       */
      public boolean hasServicePort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 service_port = 2;</code>
       */
      public int getServicePort() {
        return servicePort_;
      }
      /**
       * <code>optional int32 service_port = 2;</code>
       */
      public Builder setServicePort(int value) {
        bitField0_ |= 0x00000002;
        servicePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 service_port = 2;</code>
       */
      public Builder clearServicePort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        servicePort_ = 0;
        onChanged();
        return this;
      }

      // optional string service_argv = 3;
      private java.lang.Object serviceArgv_ = "";
      /**
       * <code>optional string service_argv = 3;</code>
       */
      public boolean hasServiceArgv() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string service_argv = 3;</code>
       */
      public java.lang.String getServiceArgv() {
        java.lang.Object ref = serviceArgv_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serviceArgv_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string service_argv = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServiceArgvBytes() {
        java.lang.Object ref = serviceArgv_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceArgv_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service_argv = 3;</code>
       */
      public Builder setServiceArgv(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serviceArgv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_argv = 3;</code>
       */
      public Builder clearServiceArgv() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serviceArgv_ = getDefaultInstance().getServiceArgv();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_argv = 3;</code>
       */
      public Builder setServiceArgvBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serviceArgv_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ohmdb.messages.StartService)
    }

    static {
      defaultInstance = new StartService(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ohmdb.messages.StartService)
  }

  public interface StopServiceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string service_name = 1;
    /**
     * <code>optional string service_name = 1;</code>
     */
    boolean hasServiceName();
    /**
     * <code>optional string service_name = 1;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>optional string service_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    // optional bool hard_stop = 2;
    /**
     * <code>optional bool hard_stop = 2;</code>
     *
     * <pre>
     * Set this to true to make it a 'hard stop', otherwise a graceful shutdown will be used.
     * </pre>
     */
    boolean hasHardStop();
    /**
     * <code>optional bool hard_stop = 2;</code>
     *
     * <pre>
     * Set this to true to make it a 'hard stop', otherwise a graceful shutdown will be used.
     * </pre>
     */
    boolean getHardStop();

    // optional string stop_reason = 3;
    /**
     * <code>optional string stop_reason = 3;</code>
     */
    boolean hasStopReason();
    /**
     * <code>optional string stop_reason = 3;</code>
     */
    java.lang.String getStopReason();
    /**
     * <code>optional string stop_reason = 3;</code>
     */
    com.google.protobuf.ByteString
        getStopReasonBytes();
  }
  /**
   * Protobuf type {@code ohmdb.messages.StopService}
   */
  public static final class StopService extends
      com.google.protobuf.GeneratedMessage
      implements StopServiceOrBuilder {
    // Use StopService.newBuilder() to construct.
    private StopService(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StopService(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StopService defaultInstance;
    public static StopService getDefaultInstance() {
      return defaultInstance;
    }

    public StopService getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StopService(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serviceName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              hardStop_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              stopReason_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_StopService_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_StopService_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ohmdb.messages.ControlMessages.StopService.class, ohmdb.messages.ControlMessages.StopService.Builder.class);
    }

    public static com.google.protobuf.Parser<StopService> PARSER =
        new com.google.protobuf.AbstractParser<StopService>() {
      public StopService parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StopService(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StopService> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string service_name = 1;
    public static final int SERVICE_NAME_FIELD_NUMBER = 1;
    private java.lang.Object serviceName_;
    /**
     * <code>optional string service_name = 1;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string service_name = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string service_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool hard_stop = 2;
    public static final int HARD_STOP_FIELD_NUMBER = 2;
    private boolean hardStop_;
    /**
     * <code>optional bool hard_stop = 2;</code>
     *
     * <pre>
     * Set this to true to make it a 'hard stop', otherwise a graceful shutdown will be used.
     * </pre>
     */
    public boolean hasHardStop() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool hard_stop = 2;</code>
     *
     * <pre>
     * Set this to true to make it a 'hard stop', otherwise a graceful shutdown will be used.
     * </pre>
     */
    public boolean getHardStop() {
      return hardStop_;
    }

    // optional string stop_reason = 3;
    public static final int STOP_REASON_FIELD_NUMBER = 3;
    private java.lang.Object stopReason_;
    /**
     * <code>optional string stop_reason = 3;</code>
     */
    public boolean hasStopReason() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string stop_reason = 3;</code>
     */
    public java.lang.String getStopReason() {
      java.lang.Object ref = stopReason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stopReason_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stop_reason = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStopReasonBytes() {
      java.lang.Object ref = stopReason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stopReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serviceName_ = "";
      hardStop_ = false;
      stopReason_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, hardStop_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStopReasonBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, hardStop_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStopReasonBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ohmdb.messages.ControlMessages.StopService parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.messages.ControlMessages.StopService parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.StopService parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.messages.ControlMessages.StopService parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.StopService parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.messages.ControlMessages.StopService parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.StopService parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ohmdb.messages.ControlMessages.StopService parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.StopService parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.messages.ControlMessages.StopService parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ohmdb.messages.ControlMessages.StopService prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ohmdb.messages.StopService}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ohmdb.messages.ControlMessages.StopServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_StopService_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_StopService_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ohmdb.messages.ControlMessages.StopService.class, ohmdb.messages.ControlMessages.StopService.Builder.class);
      }

      // Construct using ohmdb.messages.ControlMessages.StopService.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        hardStop_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        stopReason_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_StopService_descriptor;
      }

      public ohmdb.messages.ControlMessages.StopService getDefaultInstanceForType() {
        return ohmdb.messages.ControlMessages.StopService.getDefaultInstance();
      }

      public ohmdb.messages.ControlMessages.StopService build() {
        ohmdb.messages.ControlMessages.StopService result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ohmdb.messages.ControlMessages.StopService buildPartial() {
        ohmdb.messages.ControlMessages.StopService result = new ohmdb.messages.ControlMessages.StopService(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hardStop_ = hardStop_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stopReason_ = stopReason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ohmdb.messages.ControlMessages.StopService) {
          return mergeFrom((ohmdb.messages.ControlMessages.StopService)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ohmdb.messages.ControlMessages.StopService other) {
        if (other == ohmdb.messages.ControlMessages.StopService.getDefaultInstance()) return this;
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000001;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasHardStop()) {
          setHardStop(other.getHardStop());
        }
        if (other.hasStopReason()) {
          bitField0_ |= 0x00000004;
          stopReason_ = other.stopReason_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ohmdb.messages.ControlMessages.StopService parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ohmdb.messages.ControlMessages.StopService) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string service_name = 1;
      private java.lang.Object serviceName_ = "";
      /**
       * <code>optional string service_name = 1;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string service_name = 1;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string service_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service_name = 1;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_name = 1;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_name = 1;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }

      // optional bool hard_stop = 2;
      private boolean hardStop_ ;
      /**
       * <code>optional bool hard_stop = 2;</code>
       *
       * <pre>
       * Set this to true to make it a 'hard stop', otherwise a graceful shutdown will be used.
       * </pre>
       */
      public boolean hasHardStop() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool hard_stop = 2;</code>
       *
       * <pre>
       * Set this to true to make it a 'hard stop', otherwise a graceful shutdown will be used.
       * </pre>
       */
      public boolean getHardStop() {
        return hardStop_;
      }
      /**
       * <code>optional bool hard_stop = 2;</code>
       *
       * <pre>
       * Set this to true to make it a 'hard stop', otherwise a graceful shutdown will be used.
       * </pre>
       */
      public Builder setHardStop(boolean value) {
        bitField0_ |= 0x00000002;
        hardStop_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool hard_stop = 2;</code>
       *
       * <pre>
       * Set this to true to make it a 'hard stop', otherwise a graceful shutdown will be used.
       * </pre>
       */
      public Builder clearHardStop() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hardStop_ = false;
        onChanged();
        return this;
      }

      // optional string stop_reason = 3;
      private java.lang.Object stopReason_ = "";
      /**
       * <code>optional string stop_reason = 3;</code>
       */
      public boolean hasStopReason() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string stop_reason = 3;</code>
       */
      public java.lang.String getStopReason() {
        java.lang.Object ref = stopReason_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          stopReason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stop_reason = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStopReasonBytes() {
        java.lang.Object ref = stopReason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stopReason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stop_reason = 3;</code>
       */
      public Builder setStopReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stopReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stop_reason = 3;</code>
       */
      public Builder clearStopReason() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stopReason_ = getDefaultInstance().getStopReason();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stop_reason = 3;</code>
       */
      public Builder setStopReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stopReason_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ohmdb.messages.StopService)
    }

    static {
      defaultInstance = new StopService(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ohmdb.messages.StopService)
  }

  public interface CommandReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool command_success = 1;
    /**
     * <code>optional bool command_success = 1;</code>
     */
    boolean hasCommandSuccess();
    /**
     * <code>optional bool command_success = 1;</code>
     */
    boolean getCommandSuccess();

    // optional string command_stdout = 2;
    /**
     * <code>optional string command_stdout = 2;</code>
     */
    boolean hasCommandStdout();
    /**
     * <code>optional string command_stdout = 2;</code>
     */
    java.lang.String getCommandStdout();
    /**
     * <code>optional string command_stdout = 2;</code>
     */
    com.google.protobuf.ByteString
        getCommandStdoutBytes();

    // optional string command_stderr = 3;
    /**
     * <code>optional string command_stderr = 3;</code>
     */
    boolean hasCommandStderr();
    /**
     * <code>optional string command_stderr = 3;</code>
     */
    java.lang.String getCommandStderr();
    /**
     * <code>optional string command_stderr = 3;</code>
     */
    com.google.protobuf.ByteString
        getCommandStderrBytes();
  }
  /**
   * Protobuf type {@code ohmdb.messages.CommandReply}
   */
  public static final class CommandReply extends
      com.google.protobuf.GeneratedMessage
      implements CommandReplyOrBuilder {
    // Use CommandReply.newBuilder() to construct.
    private CommandReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommandReply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommandReply defaultInstance;
    public static CommandReply getDefaultInstance() {
      return defaultInstance;
    }

    public CommandReply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommandReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              commandSuccess_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              commandStdout_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              commandStderr_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_CommandReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_CommandReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ohmdb.messages.ControlMessages.CommandReply.class, ohmdb.messages.ControlMessages.CommandReply.Builder.class);
    }

    public static com.google.protobuf.Parser<CommandReply> PARSER =
        new com.google.protobuf.AbstractParser<CommandReply>() {
      public CommandReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandReply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommandReply> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool command_success = 1;
    public static final int COMMAND_SUCCESS_FIELD_NUMBER = 1;
    private boolean commandSuccess_;
    /**
     * <code>optional bool command_success = 1;</code>
     */
    public boolean hasCommandSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool command_success = 1;</code>
     */
    public boolean getCommandSuccess() {
      return commandSuccess_;
    }

    // optional string command_stdout = 2;
    public static final int COMMAND_STDOUT_FIELD_NUMBER = 2;
    private java.lang.Object commandStdout_;
    /**
     * <code>optional string command_stdout = 2;</code>
     */
    public boolean hasCommandStdout() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string command_stdout = 2;</code>
     */
    public java.lang.String getCommandStdout() {
      java.lang.Object ref = commandStdout_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          commandStdout_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string command_stdout = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCommandStdoutBytes() {
      java.lang.Object ref = commandStdout_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandStdout_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string command_stderr = 3;
    public static final int COMMAND_STDERR_FIELD_NUMBER = 3;
    private java.lang.Object commandStderr_;
    /**
     * <code>optional string command_stderr = 3;</code>
     */
    public boolean hasCommandStderr() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string command_stderr = 3;</code>
     */
    public java.lang.String getCommandStderr() {
      java.lang.Object ref = commandStderr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          commandStderr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string command_stderr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCommandStderrBytes() {
      java.lang.Object ref = commandStderr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandStderr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      commandSuccess_ = false;
      commandStdout_ = "";
      commandStderr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, commandSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCommandStdoutBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCommandStderrBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, commandSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCommandStdoutBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCommandStderrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ohmdb.messages.ControlMessages.CommandReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.messages.ControlMessages.CommandReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.CommandReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.messages.ControlMessages.CommandReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.CommandReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.messages.ControlMessages.CommandReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.CommandReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ohmdb.messages.ControlMessages.CommandReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ohmdb.messages.ControlMessages.CommandReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.messages.ControlMessages.CommandReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ohmdb.messages.ControlMessages.CommandReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ohmdb.messages.CommandReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ohmdb.messages.ControlMessages.CommandReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_CommandReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_CommandReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ohmdb.messages.ControlMessages.CommandReply.class, ohmdb.messages.ControlMessages.CommandReply.Builder.class);
      }

      // Construct using ohmdb.messages.ControlMessages.CommandReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        commandSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        commandStdout_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        commandStderr_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ohmdb.messages.ControlMessages.internal_static_ohmdb_messages_CommandReply_descriptor;
      }

      public ohmdb.messages.ControlMessages.CommandReply getDefaultInstanceForType() {
        return ohmdb.messages.ControlMessages.CommandReply.getDefaultInstance();
      }

      public ohmdb.messages.ControlMessages.CommandReply build() {
        ohmdb.messages.ControlMessages.CommandReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ohmdb.messages.ControlMessages.CommandReply buildPartial() {
        ohmdb.messages.ControlMessages.CommandReply result = new ohmdb.messages.ControlMessages.CommandReply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.commandSuccess_ = commandSuccess_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.commandStdout_ = commandStdout_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.commandStderr_ = commandStderr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ohmdb.messages.ControlMessages.CommandReply) {
          return mergeFrom((ohmdb.messages.ControlMessages.CommandReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ohmdb.messages.ControlMessages.CommandReply other) {
        if (other == ohmdb.messages.ControlMessages.CommandReply.getDefaultInstance()) return this;
        if (other.hasCommandSuccess()) {
          setCommandSuccess(other.getCommandSuccess());
        }
        if (other.hasCommandStdout()) {
          bitField0_ |= 0x00000002;
          commandStdout_ = other.commandStdout_;
          onChanged();
        }
        if (other.hasCommandStderr()) {
          bitField0_ |= 0x00000004;
          commandStderr_ = other.commandStderr_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ohmdb.messages.ControlMessages.CommandReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ohmdb.messages.ControlMessages.CommandReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool command_success = 1;
      private boolean commandSuccess_ ;
      /**
       * <code>optional bool command_success = 1;</code>
       */
      public boolean hasCommandSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool command_success = 1;</code>
       */
      public boolean getCommandSuccess() {
        return commandSuccess_;
      }
      /**
       * <code>optional bool command_success = 1;</code>
       */
      public Builder setCommandSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        commandSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool command_success = 1;</code>
       */
      public Builder clearCommandSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commandSuccess_ = false;
        onChanged();
        return this;
      }

      // optional string command_stdout = 2;
      private java.lang.Object commandStdout_ = "";
      /**
       * <code>optional string command_stdout = 2;</code>
       */
      public boolean hasCommandStdout() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string command_stdout = 2;</code>
       */
      public java.lang.String getCommandStdout() {
        java.lang.Object ref = commandStdout_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          commandStdout_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string command_stdout = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCommandStdoutBytes() {
        java.lang.Object ref = commandStdout_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commandStdout_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string command_stdout = 2;</code>
       */
      public Builder setCommandStdout(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        commandStdout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string command_stdout = 2;</code>
       */
      public Builder clearCommandStdout() {
        bitField0_ = (bitField0_ & ~0x00000002);
        commandStdout_ = getDefaultInstance().getCommandStdout();
        onChanged();
        return this;
      }
      /**
       * <code>optional string command_stdout = 2;</code>
       */
      public Builder setCommandStdoutBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        commandStdout_ = value;
        onChanged();
        return this;
      }

      // optional string command_stderr = 3;
      private java.lang.Object commandStderr_ = "";
      /**
       * <code>optional string command_stderr = 3;</code>
       */
      public boolean hasCommandStderr() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string command_stderr = 3;</code>
       */
      public java.lang.String getCommandStderr() {
        java.lang.Object ref = commandStderr_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          commandStderr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string command_stderr = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCommandStderrBytes() {
        java.lang.Object ref = commandStderr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commandStderr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string command_stderr = 3;</code>
       */
      public Builder setCommandStderr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        commandStderr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string command_stderr = 3;</code>
       */
      public Builder clearCommandStderr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        commandStderr_ = getDefaultInstance().getCommandStderr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string command_stderr = 3;</code>
       */
      public Builder setCommandStderrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        commandStderr_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ohmdb.messages.CommandReply)
    }

    static {
      defaultInstance = new CommandReply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ohmdb.messages.CommandReply)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ohmdb_messages_StartService_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ohmdb_messages_StartService_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ohmdb_messages_StopService_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ohmdb_messages_StopService_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ohmdb_messages_CommandReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ohmdb_messages_CommandReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026control_messages.proto\022\016ohmdb.messages" +
      "\"P\n\014StartService\022\024\n\014service_name\030\001 \001(\t\022\024" +
      "\n\014service_port\030\002 \001(\005\022\024\n\014service_argv\030\003 \001" +
      "(\t\"K\n\013StopService\022\024\n\014service_name\030\001 \001(\t\022" +
      "\021\n\thard_stop\030\002 \001(\010\022\023\n\013stop_reason\030\003 \001(\t\"" +
      "W\n\014CommandReply\022\027\n\017command_success\030\001 \001(\010" +
      "\022\026\n\016command_stdout\030\002 \001(\t\022\026\n\016command_stde" +
      "rr\030\003 \001(\tB\022\n\016ohmdb.messagesH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ohmdb_messages_StartService_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ohmdb_messages_StartService_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ohmdb_messages_StartService_descriptor,
              new java.lang.String[] { "ServiceName", "ServicePort", "ServiceArgv", });
          internal_static_ohmdb_messages_StopService_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ohmdb_messages_StopService_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ohmdb_messages_StopService_descriptor,
              new java.lang.String[] { "ServiceName", "HardStop", "StopReason", });
          internal_static_ohmdb_messages_CommandReply_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ohmdb_messages_CommandReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ohmdb_messages_CommandReply_descriptor,
              new java.lang.String[] { "CommandSuccess", "CommandStdout", "CommandStderr", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
