// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beacon.proto

package ohmdb.discovery;

public final class Beacon {
  private Beacon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AvailabilityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 node_id = 1;
    /**
     * <code>optional int64 node_id = 1;</code>
     *
     * <pre>
     * ID identification for this node.
     * </pre>
     */
    boolean hasNodeId();
    /**
     * <code>optional int64 node_id = 1;</code>
     *
     * <pre>
     * ID identification for this node.
     * </pre>
     */
    long getNodeId();

    // optional int32 base_network_port = 2;
    /**
     * <code>optional int32 base_network_port = 2;</code>
     *
     * <pre>
     * Network port it is reachable on
     * </pre>
     */
    boolean hasBaseNetworkPort();
    /**
     * <code>optional int32 base_network_port = 2;</code>
     *
     * <pre>
     * Network port it is reachable on
     * </pre>
     */
    int getBaseNetworkPort();

    // repeated string addresses = 3;
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    java.util.List<java.lang.String>
    getAddressesList();
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    int getAddressesCount();
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    java.lang.String getAddresses(int index);
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    com.google.protobuf.ByteString
        getAddressesBytes(int index);

    // repeated .ohmdb.election.ModuleDescriptor modules = 4;
    /**
     * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
     *
     * <pre>
     * The modules this node is running and the ports they're running on.
     * </pre>
     */
    java.util.List<ohmdb.discovery.Beacon.ModuleDescriptor> 
        getModulesList();
    /**
     * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
     *
     * <pre>
     * The modules this node is running and the ports they're running on.
     * </pre>
     */
    ohmdb.discovery.Beacon.ModuleDescriptor getModules(int index);
    /**
     * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
     *
     * <pre>
     * The modules this node is running and the ports they're running on.
     * </pre>
     */
    int getModulesCount();
    /**
     * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
     *
     * <pre>
     * The modules this node is running and the ports they're running on.
     * </pre>
     */
    java.util.List<? extends ohmdb.discovery.Beacon.ModuleDescriptorOrBuilder> 
        getModulesOrBuilderList();
    /**
     * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
     *
     * <pre>
     * The modules this node is running and the ports they're running on.
     * </pre>
     */
    ohmdb.discovery.Beacon.ModuleDescriptorOrBuilder getModulesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ohmdb.election.Availability}
   *
   * <pre>
   * An availability broadcast
   * </pre>
   */
  public static final class Availability extends
      com.google.protobuf.GeneratedMessage
      implements AvailabilityOrBuilder {
    // Use Availability.newBuilder() to construct.
    private Availability(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Availability(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Availability defaultInstance;
    public static Availability getDefaultInstance() {
      return defaultInstance;
    }

    public Availability getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Availability(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nodeId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              baseNetworkPort_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                addresses_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              addresses_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                modules_ = new java.util.ArrayList<ohmdb.discovery.Beacon.ModuleDescriptor>();
                mutable_bitField0_ |= 0x00000008;
              }
              modules_.add(input.readMessage(ohmdb.discovery.Beacon.ModuleDescriptor.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          addresses_ = new com.google.protobuf.UnmodifiableLazyStringList(addresses_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          modules_ = java.util.Collections.unmodifiableList(modules_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ohmdb.discovery.Beacon.internal_static_ohmdb_election_Availability_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ohmdb.discovery.Beacon.internal_static_ohmdb_election_Availability_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ohmdb.discovery.Beacon.Availability.class, ohmdb.discovery.Beacon.Availability.Builder.class);
    }

    public static com.google.protobuf.Parser<Availability> PARSER =
        new com.google.protobuf.AbstractParser<Availability>() {
      public Availability parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Availability(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Availability> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 node_id = 1;
    public static final int NODE_ID_FIELD_NUMBER = 1;
    private long nodeId_;
    /**
     * <code>optional int64 node_id = 1;</code>
     *
     * <pre>
     * ID identification for this node.
     * </pre>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 node_id = 1;</code>
     *
     * <pre>
     * ID identification for this node.
     * </pre>
     */
    public long getNodeId() {
      return nodeId_;
    }

    // optional int32 base_network_port = 2;
    public static final int BASE_NETWORK_PORT_FIELD_NUMBER = 2;
    private int baseNetworkPort_;
    /**
     * <code>optional int32 base_network_port = 2;</code>
     *
     * <pre>
     * Network port it is reachable on
     * </pre>
     */
    public boolean hasBaseNetworkPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 base_network_port = 2;</code>
     *
     * <pre>
     * Network port it is reachable on
     * </pre>
     */
    public int getBaseNetworkPort() {
      return baseNetworkPort_;
    }

    // repeated string addresses = 3;
    public static final int ADDRESSES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList addresses_;
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    public java.util.List<java.lang.String>
        getAddressesList() {
      return addresses_;
    }
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    public java.lang.String getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAddressesBytes(int index) {
      return addresses_.getByteString(index);
    }

    // repeated .ohmdb.election.ModuleDescriptor modules = 4;
    public static final int MODULES_FIELD_NUMBER = 4;
    private java.util.List<ohmdb.discovery.Beacon.ModuleDescriptor> modules_;
    /**
     * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
     *
     * <pre>
     * The modules this node is running and the ports they're running on.
     * </pre>
     */
    public java.util.List<ohmdb.discovery.Beacon.ModuleDescriptor> getModulesList() {
      return modules_;
    }
    /**
     * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
     *
     * <pre>
     * The modules this node is running and the ports they're running on.
     * </pre>
     */
    public java.util.List<? extends ohmdb.discovery.Beacon.ModuleDescriptorOrBuilder> 
        getModulesOrBuilderList() {
      return modules_;
    }
    /**
     * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
     *
     * <pre>
     * The modules this node is running and the ports they're running on.
     * </pre>
     */
    public int getModulesCount() {
      return modules_.size();
    }
    /**
     * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
     *
     * <pre>
     * The modules this node is running and the ports they're running on.
     * </pre>
     */
    public ohmdb.discovery.Beacon.ModuleDescriptor getModules(int index) {
      return modules_.get(index);
    }
    /**
     * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
     *
     * <pre>
     * The modules this node is running and the ports they're running on.
     * </pre>
     */
    public ohmdb.discovery.Beacon.ModuleDescriptorOrBuilder getModulesOrBuilder(
        int index) {
      return modules_.get(index);
    }

    private void initFields() {
      nodeId_ = 0L;
      baseNetworkPort_ = 0;
      addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      modules_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, nodeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, baseNetworkPort_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        output.writeBytes(3, addresses_.getByteString(i));
      }
      for (int i = 0; i < modules_.size(); i++) {
        output.writeMessage(4, modules_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nodeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, baseNetworkPort_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addresses_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(addresses_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getAddressesList().size();
      }
      for (int i = 0; i < modules_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, modules_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ohmdb.discovery.Beacon.Availability parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.Availability parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ohmdb.discovery.Beacon.Availability parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ohmdb.discovery.Beacon.Availability prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ohmdb.election.Availability}
     *
     * <pre>
     * An availability broadcast
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ohmdb.discovery.Beacon.AvailabilityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ohmdb.discovery.Beacon.internal_static_ohmdb_election_Availability_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ohmdb.discovery.Beacon.internal_static_ohmdb_election_Availability_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ohmdb.discovery.Beacon.Availability.class, ohmdb.discovery.Beacon.Availability.Builder.class);
      }

      // Construct using ohmdb.discovery.Beacon.Availability.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getModulesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nodeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        baseNetworkPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (modulesBuilder_ == null) {
          modules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          modulesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ohmdb.discovery.Beacon.internal_static_ohmdb_election_Availability_descriptor;
      }

      public ohmdb.discovery.Beacon.Availability getDefaultInstanceForType() {
        return ohmdb.discovery.Beacon.Availability.getDefaultInstance();
      }

      public ohmdb.discovery.Beacon.Availability build() {
        ohmdb.discovery.Beacon.Availability result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ohmdb.discovery.Beacon.Availability buildPartial() {
        ohmdb.discovery.Beacon.Availability result = new ohmdb.discovery.Beacon.Availability(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.baseNetworkPort_ = baseNetworkPort_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          addresses_ = new com.google.protobuf.UnmodifiableLazyStringList(
              addresses_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.addresses_ = addresses_;
        if (modulesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            modules_ = java.util.Collections.unmodifiableList(modules_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.modules_ = modules_;
        } else {
          result.modules_ = modulesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ohmdb.discovery.Beacon.Availability) {
          return mergeFrom((ohmdb.discovery.Beacon.Availability)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ohmdb.discovery.Beacon.Availability other) {
        if (other == ohmdb.discovery.Beacon.Availability.getDefaultInstance()) return this;
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (other.hasBaseNetworkPort()) {
          setBaseNetworkPort(other.getBaseNetworkPort());
        }
        if (!other.addresses_.isEmpty()) {
          if (addresses_.isEmpty()) {
            addresses_ = other.addresses_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAddressesIsMutable();
            addresses_.addAll(other.addresses_);
          }
          onChanged();
        }
        if (modulesBuilder_ == null) {
          if (!other.modules_.isEmpty()) {
            if (modules_.isEmpty()) {
              modules_ = other.modules_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureModulesIsMutable();
              modules_.addAll(other.modules_);
            }
            onChanged();
          }
        } else {
          if (!other.modules_.isEmpty()) {
            if (modulesBuilder_.isEmpty()) {
              modulesBuilder_.dispose();
              modulesBuilder_ = null;
              modules_ = other.modules_;
              bitField0_ = (bitField0_ & ~0x00000008);
              modulesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getModulesFieldBuilder() : null;
            } else {
              modulesBuilder_.addAllMessages(other.modules_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ohmdb.discovery.Beacon.Availability parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ohmdb.discovery.Beacon.Availability) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 node_id = 1;
      private long nodeId_ ;
      /**
       * <code>optional int64 node_id = 1;</code>
       *
       * <pre>
       * ID identification for this node.
       * </pre>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 node_id = 1;</code>
       *
       * <pre>
       * ID identification for this node.
       * </pre>
       */
      public long getNodeId() {
        return nodeId_;
      }
      /**
       * <code>optional int64 node_id = 1;</code>
       *
       * <pre>
       * ID identification for this node.
       * </pre>
       */
      public Builder setNodeId(long value) {
        bitField0_ |= 0x00000001;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 node_id = 1;</code>
       *
       * <pre>
       * ID identification for this node.
       * </pre>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 base_network_port = 2;
      private int baseNetworkPort_ ;
      /**
       * <code>optional int32 base_network_port = 2;</code>
       *
       * <pre>
       * Network port it is reachable on
       * </pre>
       */
      public boolean hasBaseNetworkPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 base_network_port = 2;</code>
       *
       * <pre>
       * Network port it is reachable on
       * </pre>
       */
      public int getBaseNetworkPort() {
        return baseNetworkPort_;
      }
      /**
       * <code>optional int32 base_network_port = 2;</code>
       *
       * <pre>
       * Network port it is reachable on
       * </pre>
       */
      public Builder setBaseNetworkPort(int value) {
        bitField0_ |= 0x00000002;
        baseNetworkPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 base_network_port = 2;</code>
       *
       * <pre>
       * Network port it is reachable on
       * </pre>
       */
      public Builder clearBaseNetworkPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        baseNetworkPort_ = 0;
        onChanged();
        return this;
      }

      // repeated string addresses = 3;
      private com.google.protobuf.LazyStringList addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          addresses_ = new com.google.protobuf.LazyStringArrayList(addresses_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public java.util.List<java.lang.String>
          getAddressesList() {
        return java.util.Collections.unmodifiableList(addresses_);
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public int getAddressesCount() {
        return addresses_.size();
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public java.lang.String getAddresses(int index) {
        return addresses_.get(index);
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAddressesBytes(int index) {
        return addresses_.getByteString(index);
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public Builder setAddresses(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public Builder addAddresses(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public Builder addAllAddresses(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddressesIsMutable();
        super.addAll(values, addresses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public Builder clearAddresses() {
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public Builder addAddressesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }

      // repeated .ohmdb.election.ModuleDescriptor modules = 4;
      private java.util.List<ohmdb.discovery.Beacon.ModuleDescriptor> modules_ =
        java.util.Collections.emptyList();
      private void ensureModulesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          modules_ = new java.util.ArrayList<ohmdb.discovery.Beacon.ModuleDescriptor>(modules_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ohmdb.discovery.Beacon.ModuleDescriptor, ohmdb.discovery.Beacon.ModuleDescriptor.Builder, ohmdb.discovery.Beacon.ModuleDescriptorOrBuilder> modulesBuilder_;

      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public java.util.List<ohmdb.discovery.Beacon.ModuleDescriptor> getModulesList() {
        if (modulesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(modules_);
        } else {
          return modulesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public int getModulesCount() {
        if (modulesBuilder_ == null) {
          return modules_.size();
        } else {
          return modulesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public ohmdb.discovery.Beacon.ModuleDescriptor getModules(int index) {
        if (modulesBuilder_ == null) {
          return modules_.get(index);
        } else {
          return modulesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public Builder setModules(
          int index, ohmdb.discovery.Beacon.ModuleDescriptor value) {
        if (modulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModulesIsMutable();
          modules_.set(index, value);
          onChanged();
        } else {
          modulesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public Builder setModules(
          int index, ohmdb.discovery.Beacon.ModuleDescriptor.Builder builderForValue) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.set(index, builderForValue.build());
          onChanged();
        } else {
          modulesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public Builder addModules(ohmdb.discovery.Beacon.ModuleDescriptor value) {
        if (modulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModulesIsMutable();
          modules_.add(value);
          onChanged();
        } else {
          modulesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public Builder addModules(
          int index, ohmdb.discovery.Beacon.ModuleDescriptor value) {
        if (modulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModulesIsMutable();
          modules_.add(index, value);
          onChanged();
        } else {
          modulesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public Builder addModules(
          ohmdb.discovery.Beacon.ModuleDescriptor.Builder builderForValue) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.add(builderForValue.build());
          onChanged();
        } else {
          modulesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public Builder addModules(
          int index, ohmdb.discovery.Beacon.ModuleDescriptor.Builder builderForValue) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.add(index, builderForValue.build());
          onChanged();
        } else {
          modulesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public Builder addAllModules(
          java.lang.Iterable<? extends ohmdb.discovery.Beacon.ModuleDescriptor> values) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          super.addAll(values, modules_);
          onChanged();
        } else {
          modulesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public Builder clearModules() {
        if (modulesBuilder_ == null) {
          modules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          modulesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public Builder removeModules(int index) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.remove(index);
          onChanged();
        } else {
          modulesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public ohmdb.discovery.Beacon.ModuleDescriptor.Builder getModulesBuilder(
          int index) {
        return getModulesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public ohmdb.discovery.Beacon.ModuleDescriptorOrBuilder getModulesOrBuilder(
          int index) {
        if (modulesBuilder_ == null) {
          return modules_.get(index);  } else {
          return modulesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public java.util.List<? extends ohmdb.discovery.Beacon.ModuleDescriptorOrBuilder> 
           getModulesOrBuilderList() {
        if (modulesBuilder_ != null) {
          return modulesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(modules_);
        }
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public ohmdb.discovery.Beacon.ModuleDescriptor.Builder addModulesBuilder() {
        return getModulesFieldBuilder().addBuilder(
            ohmdb.discovery.Beacon.ModuleDescriptor.getDefaultInstance());
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public ohmdb.discovery.Beacon.ModuleDescriptor.Builder addModulesBuilder(
          int index) {
        return getModulesFieldBuilder().addBuilder(
            index, ohmdb.discovery.Beacon.ModuleDescriptor.getDefaultInstance());
      }
      /**
       * <code>repeated .ohmdb.election.ModuleDescriptor modules = 4;</code>
       *
       * <pre>
       * The modules this node is running and the ports they're running on.
       * </pre>
       */
      public java.util.List<ohmdb.discovery.Beacon.ModuleDescriptor.Builder> 
           getModulesBuilderList() {
        return getModulesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ohmdb.discovery.Beacon.ModuleDescriptor, ohmdb.discovery.Beacon.ModuleDescriptor.Builder, ohmdb.discovery.Beacon.ModuleDescriptorOrBuilder> 
          getModulesFieldBuilder() {
        if (modulesBuilder_ == null) {
          modulesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ohmdb.discovery.Beacon.ModuleDescriptor, ohmdb.discovery.Beacon.ModuleDescriptor.Builder, ohmdb.discovery.Beacon.ModuleDescriptorOrBuilder>(
                  modules_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          modules_ = null;
        }
        return modulesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ohmdb.election.Availability)
    }

    static {
      defaultInstance = new Availability(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ohmdb.election.Availability)
  }

  public interface ModuleDescriptorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .ohmdb.messages.ModuleType module = 1;
    /**
     * <code>optional .ohmdb.messages.ModuleType module = 1;</code>
     */
    boolean hasModule();
    /**
     * <code>optional .ohmdb.messages.ModuleType module = 1;</code>
     */
    ohmdb.messages.ControlMessages.ModuleType getModule();

    // optional uint32 module_port = 2;
    /**
     * <code>optional uint32 module_port = 2;</code>
     */
    boolean hasModulePort();
    /**
     * <code>optional uint32 module_port = 2;</code>
     */
    int getModulePort();
  }
  /**
   * Protobuf type {@code ohmdb.election.ModuleDescriptor}
   *
   * <pre>
   * Module name to module port mapping.
   * </pre>
   */
  public static final class ModuleDescriptor extends
      com.google.protobuf.GeneratedMessage
      implements ModuleDescriptorOrBuilder {
    // Use ModuleDescriptor.newBuilder() to construct.
    private ModuleDescriptor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ModuleDescriptor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ModuleDescriptor defaultInstance;
    public static ModuleDescriptor getDefaultInstance() {
      return defaultInstance;
    }

    public ModuleDescriptor getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ModuleDescriptor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ohmdb.messages.ControlMessages.ModuleType value = ohmdb.messages.ControlMessages.ModuleType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                module_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              modulePort_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ohmdb.discovery.Beacon.internal_static_ohmdb_election_ModuleDescriptor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ohmdb.discovery.Beacon.internal_static_ohmdb_election_ModuleDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ohmdb.discovery.Beacon.ModuleDescriptor.class, ohmdb.discovery.Beacon.ModuleDescriptor.Builder.class);
    }

    public static com.google.protobuf.Parser<ModuleDescriptor> PARSER =
        new com.google.protobuf.AbstractParser<ModuleDescriptor>() {
      public ModuleDescriptor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModuleDescriptor(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ModuleDescriptor> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .ohmdb.messages.ModuleType module = 1;
    public static final int MODULE_FIELD_NUMBER = 1;
    private ohmdb.messages.ControlMessages.ModuleType module_;
    /**
     * <code>optional .ohmdb.messages.ModuleType module = 1;</code>
     */
    public boolean hasModule() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ohmdb.messages.ModuleType module = 1;</code>
     */
    public ohmdb.messages.ControlMessages.ModuleType getModule() {
      return module_;
    }

    // optional uint32 module_port = 2;
    public static final int MODULE_PORT_FIELD_NUMBER = 2;
    private int modulePort_;
    /**
     * <code>optional uint32 module_port = 2;</code>
     */
    public boolean hasModulePort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 module_port = 2;</code>
     */
    public int getModulePort() {
      return modulePort_;
    }

    private void initFields() {
      module_ = ohmdb.messages.ControlMessages.ModuleType.Discovery;
      modulePort_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, module_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, modulePort_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, module_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, modulePort_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ohmdb.discovery.Beacon.ModuleDescriptor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.discovery.Beacon.ModuleDescriptor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.ModuleDescriptor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.discovery.Beacon.ModuleDescriptor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.ModuleDescriptor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.discovery.Beacon.ModuleDescriptor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.ModuleDescriptor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ohmdb.discovery.Beacon.ModuleDescriptor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.ModuleDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.discovery.Beacon.ModuleDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ohmdb.discovery.Beacon.ModuleDescriptor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ohmdb.election.ModuleDescriptor}
     *
     * <pre>
     * Module name to module port mapping.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ohmdb.discovery.Beacon.ModuleDescriptorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ohmdb.discovery.Beacon.internal_static_ohmdb_election_ModuleDescriptor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ohmdb.discovery.Beacon.internal_static_ohmdb_election_ModuleDescriptor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ohmdb.discovery.Beacon.ModuleDescriptor.class, ohmdb.discovery.Beacon.ModuleDescriptor.Builder.class);
      }

      // Construct using ohmdb.discovery.Beacon.ModuleDescriptor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        module_ = ohmdb.messages.ControlMessages.ModuleType.Discovery;
        bitField0_ = (bitField0_ & ~0x00000001);
        modulePort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ohmdb.discovery.Beacon.internal_static_ohmdb_election_ModuleDescriptor_descriptor;
      }

      public ohmdb.discovery.Beacon.ModuleDescriptor getDefaultInstanceForType() {
        return ohmdb.discovery.Beacon.ModuleDescriptor.getDefaultInstance();
      }

      public ohmdb.discovery.Beacon.ModuleDescriptor build() {
        ohmdb.discovery.Beacon.ModuleDescriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ohmdb.discovery.Beacon.ModuleDescriptor buildPartial() {
        ohmdb.discovery.Beacon.ModuleDescriptor result = new ohmdb.discovery.Beacon.ModuleDescriptor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.module_ = module_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.modulePort_ = modulePort_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ohmdb.discovery.Beacon.ModuleDescriptor) {
          return mergeFrom((ohmdb.discovery.Beacon.ModuleDescriptor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ohmdb.discovery.Beacon.ModuleDescriptor other) {
        if (other == ohmdb.discovery.Beacon.ModuleDescriptor.getDefaultInstance()) return this;
        if (other.hasModule()) {
          setModule(other.getModule());
        }
        if (other.hasModulePort()) {
          setModulePort(other.getModulePort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ohmdb.discovery.Beacon.ModuleDescriptor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ohmdb.discovery.Beacon.ModuleDescriptor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .ohmdb.messages.ModuleType module = 1;
      private ohmdb.messages.ControlMessages.ModuleType module_ = ohmdb.messages.ControlMessages.ModuleType.Discovery;
      /**
       * <code>optional .ohmdb.messages.ModuleType module = 1;</code>
       */
      public boolean hasModule() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .ohmdb.messages.ModuleType module = 1;</code>
       */
      public ohmdb.messages.ControlMessages.ModuleType getModule() {
        return module_;
      }
      /**
       * <code>optional .ohmdb.messages.ModuleType module = 1;</code>
       */
      public Builder setModule(ohmdb.messages.ControlMessages.ModuleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        module_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ohmdb.messages.ModuleType module = 1;</code>
       */
      public Builder clearModule() {
        bitField0_ = (bitField0_ & ~0x00000001);
        module_ = ohmdb.messages.ControlMessages.ModuleType.Discovery;
        onChanged();
        return this;
      }

      // optional uint32 module_port = 2;
      private int modulePort_ ;
      /**
       * <code>optional uint32 module_port = 2;</code>
       */
      public boolean hasModulePort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 module_port = 2;</code>
       */
      public int getModulePort() {
        return modulePort_;
      }
      /**
       * <code>optional uint32 module_port = 2;</code>
       */
      public Builder setModulePort(int value) {
        bitField0_ |= 0x00000002;
        modulePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 module_port = 2;</code>
       */
      public Builder clearModulePort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        modulePort_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ohmdb.election.ModuleDescriptor)
    }

    static {
      defaultInstance = new ModuleDescriptor(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ohmdb.election.ModuleDescriptor)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ohmdb_election_Availability_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ohmdb_election_Availability_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ohmdb_election_ModuleDescriptor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ohmdb_election_ModuleDescriptor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014beacon.proto\022\016ohmdb.election\032\026control_" +
      "messages.proto\"\200\001\n\014Availability\022\017\n\007node_" +
      "id\030\001 \001(\003\022\031\n\021base_network_port\030\002 \001(\005\022\021\n\ta" +
      "ddresses\030\003 \003(\t\0221\n\007modules\030\004 \003(\0132 .ohmdb." +
      "election.ModuleDescriptor\"S\n\020ModuleDescr" +
      "iptor\022*\n\006module\030\001 \001(\0162\032.ohmdb.messages.M" +
      "oduleType\022\023\n\013module_port\030\002 \001(\rB\023\n\017ohmdb." +
      "discoveryH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ohmdb_election_Availability_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ohmdb_election_Availability_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ohmdb_election_Availability_descriptor,
              new java.lang.String[] { "NodeId", "BaseNetworkPort", "Addresses", "Modules", });
          internal_static_ohmdb_election_ModuleDescriptor_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ohmdb_election_ModuleDescriptor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ohmdb_election_ModuleDescriptor_descriptor,
              new java.lang.String[] { "Module", "ModulePort", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ohmdb.messages.ControlMessages.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
