// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beacon.proto

package ohmdb.discovery;

public final class Beacon {
  private Beacon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AvailabilityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 node_id = 1;
    /**
     * <code>optional int64 node_id = 1;</code>
     *
     * <pre>
     * ID identification for this node.
     * </pre>
     */
    boolean hasNodeId();
    /**
     * <code>optional int64 node_id = 1;</code>
     *
     * <pre>
     * ID identification for this node.
     * </pre>
     */
    long getNodeId();

    // optional int32 base_network_port = 2;
    /**
     * <code>optional int32 base_network_port = 2;</code>
     *
     * <pre>
     * Network port it is reachable on
     * </pre>
     */
    boolean hasBaseNetworkPort();
    /**
     * <code>optional int32 base_network_port = 2;</code>
     *
     * <pre>
     * Network port it is reachable on
     * </pre>
     */
    int getBaseNetworkPort();

    // repeated string addresses = 3;
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    java.util.List<java.lang.String>
    getAddressesList();
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    int getAddressesCount();
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    java.lang.String getAddresses(int index);
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    com.google.protobuf.ByteString
        getAddressesBytes(int index);
  }
  /**
   * Protobuf type {@code ohmdb.election.Availability}
   *
   * <pre>
   * An availability broadcast
   * </pre>
   */
  public static final class Availability extends
      com.google.protobuf.GeneratedMessage
      implements AvailabilityOrBuilder {
    // Use Availability.newBuilder() to construct.
    private Availability(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Availability(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Availability defaultInstance;
    public static Availability getDefaultInstance() {
      return defaultInstance;
    }

    public Availability getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Availability(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nodeId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              baseNetworkPort_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                addresses_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              addresses_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          addresses_ = new com.google.protobuf.UnmodifiableLazyStringList(addresses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ohmdb.discovery.Beacon.internal_static_ohmdb_election_Availability_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ohmdb.discovery.Beacon.internal_static_ohmdb_election_Availability_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ohmdb.discovery.Beacon.Availability.class, ohmdb.discovery.Beacon.Availability.Builder.class);
    }

    public static com.google.protobuf.Parser<Availability> PARSER =
        new com.google.protobuf.AbstractParser<Availability>() {
      public Availability parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Availability(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Availability> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 node_id = 1;
    public static final int NODE_ID_FIELD_NUMBER = 1;
    private long nodeId_;
    /**
     * <code>optional int64 node_id = 1;</code>
     *
     * <pre>
     * ID identification for this node.
     * </pre>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 node_id = 1;</code>
     *
     * <pre>
     * ID identification for this node.
     * </pre>
     */
    public long getNodeId() {
      return nodeId_;
    }

    // optional int32 base_network_port = 2;
    public static final int BASE_NETWORK_PORT_FIELD_NUMBER = 2;
    private int baseNetworkPort_;
    /**
     * <code>optional int32 base_network_port = 2;</code>
     *
     * <pre>
     * Network port it is reachable on
     * </pre>
     */
    public boolean hasBaseNetworkPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 base_network_port = 2;</code>
     *
     * <pre>
     * Network port it is reachable on
     * </pre>
     */
    public int getBaseNetworkPort() {
      return baseNetworkPort_;
    }

    // repeated string addresses = 3;
    public static final int ADDRESSES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList addresses_;
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    public java.util.List<java.lang.String>
        getAddressesList() {
      return addresses_;
    }
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    public java.lang.String getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <code>repeated string addresses = 3;</code>
     *
     * <pre>
     * The network addresses we can be reached at
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAddressesBytes(int index) {
      return addresses_.getByteString(index);
    }

    private void initFields() {
      nodeId_ = 0L;
      baseNetworkPort_ = 0;
      addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, nodeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, baseNetworkPort_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        output.writeBytes(3, addresses_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nodeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, baseNetworkPort_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addresses_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(addresses_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getAddressesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ohmdb.discovery.Beacon.Availability parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.Availability parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ohmdb.discovery.Beacon.Availability parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ohmdb.discovery.Beacon.Availability parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ohmdb.discovery.Beacon.Availability prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ohmdb.election.Availability}
     *
     * <pre>
     * An availability broadcast
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ohmdb.discovery.Beacon.AvailabilityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ohmdb.discovery.Beacon.internal_static_ohmdb_election_Availability_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ohmdb.discovery.Beacon.internal_static_ohmdb_election_Availability_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ohmdb.discovery.Beacon.Availability.class, ohmdb.discovery.Beacon.Availability.Builder.class);
      }

      // Construct using ohmdb.discovery.Beacon.Availability.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nodeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        baseNetworkPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ohmdb.discovery.Beacon.internal_static_ohmdb_election_Availability_descriptor;
      }

      public ohmdb.discovery.Beacon.Availability getDefaultInstanceForType() {
        return ohmdb.discovery.Beacon.Availability.getDefaultInstance();
      }

      public ohmdb.discovery.Beacon.Availability build() {
        ohmdb.discovery.Beacon.Availability result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ohmdb.discovery.Beacon.Availability buildPartial() {
        ohmdb.discovery.Beacon.Availability result = new ohmdb.discovery.Beacon.Availability(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.baseNetworkPort_ = baseNetworkPort_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          addresses_ = new com.google.protobuf.UnmodifiableLazyStringList(
              addresses_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.addresses_ = addresses_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ohmdb.discovery.Beacon.Availability) {
          return mergeFrom((ohmdb.discovery.Beacon.Availability)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ohmdb.discovery.Beacon.Availability other) {
        if (other == ohmdb.discovery.Beacon.Availability.getDefaultInstance()) return this;
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (other.hasBaseNetworkPort()) {
          setBaseNetworkPort(other.getBaseNetworkPort());
        }
        if (!other.addresses_.isEmpty()) {
          if (addresses_.isEmpty()) {
            addresses_ = other.addresses_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAddressesIsMutable();
            addresses_.addAll(other.addresses_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ohmdb.discovery.Beacon.Availability parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ohmdb.discovery.Beacon.Availability) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 node_id = 1;
      private long nodeId_ ;
      /**
       * <code>optional int64 node_id = 1;</code>
       *
       * <pre>
       * ID identification for this node.
       * </pre>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 node_id = 1;</code>
       *
       * <pre>
       * ID identification for this node.
       * </pre>
       */
      public long getNodeId() {
        return nodeId_;
      }
      /**
       * <code>optional int64 node_id = 1;</code>
       *
       * <pre>
       * ID identification for this node.
       * </pre>
       */
      public Builder setNodeId(long value) {
        bitField0_ |= 0x00000001;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 node_id = 1;</code>
       *
       * <pre>
       * ID identification for this node.
       * </pre>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 base_network_port = 2;
      private int baseNetworkPort_ ;
      /**
       * <code>optional int32 base_network_port = 2;</code>
       *
       * <pre>
       * Network port it is reachable on
       * </pre>
       */
      public boolean hasBaseNetworkPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 base_network_port = 2;</code>
       *
       * <pre>
       * Network port it is reachable on
       * </pre>
       */
      public int getBaseNetworkPort() {
        return baseNetworkPort_;
      }
      /**
       * <code>optional int32 base_network_port = 2;</code>
       *
       * <pre>
       * Network port it is reachable on
       * </pre>
       */
      public Builder setBaseNetworkPort(int value) {
        bitField0_ |= 0x00000002;
        baseNetworkPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 base_network_port = 2;</code>
       *
       * <pre>
       * Network port it is reachable on
       * </pre>
       */
      public Builder clearBaseNetworkPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        baseNetworkPort_ = 0;
        onChanged();
        return this;
      }

      // repeated string addresses = 3;
      private com.google.protobuf.LazyStringList addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          addresses_ = new com.google.protobuf.LazyStringArrayList(addresses_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public java.util.List<java.lang.String>
          getAddressesList() {
        return java.util.Collections.unmodifiableList(addresses_);
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public int getAddressesCount() {
        return addresses_.size();
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public java.lang.String getAddresses(int index) {
        return addresses_.get(index);
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAddressesBytes(int index) {
        return addresses_.getByteString(index);
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public Builder setAddresses(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public Builder addAddresses(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public Builder addAllAddresses(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddressesIsMutable();
        super.addAll(values, addresses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public Builder clearAddresses() {
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 3;</code>
       *
       * <pre>
       * The network addresses we can be reached at
       * </pre>
       */
      public Builder addAddressesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ohmdb.election.Availability)
    }

    static {
      defaultInstance = new Availability(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ohmdb.election.Availability)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ohmdb_election_Availability_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ohmdb_election_Availability_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014beacon.proto\022\016ohmdb.election\"M\n\014Availa" +
      "bility\022\017\n\007node_id\030\001 \001(\003\022\031\n\021base_network_" +
      "port\030\002 \001(\005\022\021\n\taddresses\030\003 \003(\tB\023\n\017ohmdb.d" +
      "iscoveryH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ohmdb_election_Availability_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ohmdb_election_Availability_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ohmdb_election_Availability_descriptor,
              new java.lang.String[] { "NodeId", "BaseNetworkPort", "Addresses", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
